# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zinnia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zinnia.Entry', verbose_name='entry')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(help_text='Used for gallery', upload_to=news.models.photo_upload_to_dispatcher)),
                ('credit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entryphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Photo'),
        ),
    ]
