# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('index', models.BooleanField(default=True, verbose_name='index')),
            ],
        ),
    ]
