# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=50)),
                ('src', models.ImageField(help_text='Tamano recomendado: 640x640', upload_to='uploads/ads')),
                ('link', models.CharField(blank=True, max_length=50, null=True)),
                ('index', models.BooleanField(default=False, verbose_name='index')),
                ('article', models.BooleanField(default=False, verbose_name='article')),
            ],
        ),
    ]
