# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
